################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
ASM_SRCS += \
../src/_csl_intcIntrEnDisRes.asm \
../src/_csl_intcIsrDispatch.asm 

C_SRCS += \
../src/BitDescrambling.c \
../src/Exception.c \
../src/FunctionHook.c \
../src/KeyStone_DDR_Init.c \
../src/KeyStone_Multicore_Navigator_drv.c \
../src/KeyStone_SRIO_Init.c \
../src/KeyStone_Timer_Init.c \
../src/KeyStone_common.c \
../src/Keystone_SRIO_drv.c \
../src/Keystone_Serdes_init.c \
../src/MNav_funct.c \
../src/SRIO_2DSP_Test.c \
../src/SRIO_PktDMA_Init.c \
../src/SRIO_external_forward_back_Test.c \
../src/SRIO_external_line_loopback_Test.c \
../src/SRIO_internal_loopback_Test.c \
../src/SRIO_loopback_Test.c \
../src/TSC.c \
../src/VCP2_Channel_Density.c \
../src/_csl_intcResource.c \
../src/bcp_device.c \
../src/bcp_func.c \
../src/bcp_lte_pdsch_receive.c \
../src/cc_conv_decoder.c \
../src/cc_conv_derate_matching.c \
../src/chan_eq_sdm.c \
../src/chan_est.c \
../src/chan_interp.c \
../src/classify1_bin.c \
../src/classify2_bin.c \
../src/cppi_desc.c \
../src/cppi_device.c \
../src/cppi_drv.c \
../src/cppi_listlib.c \
../src/crc_decoder.c \
../src/crs_prb_demapping.c \
../src/csl_chip.c \
../src/dci_process.c \
../src/demodulation.c \
../src/fftc_func.c \
../src/freq_agc.c \
../src/ifft_data.c \
../src/layerdemapping.c \
../src/lte_dl_receiver_process.c \
../src/osal.c \
../src/pa.c \
../src/painit.c \
../src/pam_bin.c \
../src/para_update.c \
../src/phich_detect.c \
../src/pl_const.c \
../src/prb_demapping_all.c \
../src/qmss_acc.c \
../src/qmss_device.c \
../src/qmss_drv.c \
../src/rs_basic_gen.c \
../src/singlecore_osal.c \
../src/srio_debug.c \
../src/system_init.c \
../src/system_init_var.c \
../src/tcp3d_device.c \
../src/tcp3d_fun.c \
../src/tcp3d_itg.c \
../src/tcp3d_pdsch.c \
../src/vcp2_common.c \
../src/view_ale_table.c 

OBJS += \
./src/BitDescrambling.obj \
./src/Exception.obj \
./src/FunctionHook.obj \
./src/KeyStone_DDR_Init.obj \
./src/KeyStone_Multicore_Navigator_drv.obj \
./src/KeyStone_SRIO_Init.obj \
./src/KeyStone_Timer_Init.obj \
./src/KeyStone_common.obj \
./src/Keystone_SRIO_drv.obj \
./src/Keystone_Serdes_init.obj \
./src/MNav_funct.obj \
./src/SRIO_2DSP_Test.obj \
./src/SRIO_PktDMA_Init.obj \
./src/SRIO_external_forward_back_Test.obj \
./src/SRIO_external_line_loopback_Test.obj \
./src/SRIO_internal_loopback_Test.obj \
./src/SRIO_loopback_Test.obj \
./src/TSC.obj \
./src/VCP2_Channel_Density.obj \
./src/_csl_intcIntrEnDisRes.obj \
./src/_csl_intcIsrDispatch.obj \
./src/_csl_intcResource.obj \
./src/bcp_device.obj \
./src/bcp_func.obj \
./src/bcp_lte_pdsch_receive.obj \
./src/cc_conv_decoder.obj \
./src/cc_conv_derate_matching.obj \
./src/chan_eq_sdm.obj \
./src/chan_est.obj \
./src/chan_interp.obj \
./src/classify1_bin.obj \
./src/classify2_bin.obj \
./src/cppi_desc.obj \
./src/cppi_device.obj \
./src/cppi_drv.obj \
./src/cppi_listlib.obj \
./src/crc_decoder.obj \
./src/crs_prb_demapping.obj \
./src/csl_chip.obj \
./src/dci_process.obj \
./src/demodulation.obj \
./src/fftc_func.obj \
./src/freq_agc.obj \
./src/ifft_data.obj \
./src/layerdemapping.obj \
./src/lte_dl_receiver_process.obj \
./src/osal.obj \
./src/pa.obj \
./src/painit.obj \
./src/pam_bin.obj \
./src/para_update.obj \
./src/phich_detect.obj \
./src/pl_const.obj \
./src/prb_demapping_all.obj \
./src/qmss_acc.obj \
./src/qmss_device.obj \
./src/qmss_drv.obj \
./src/rs_basic_gen.obj \
./src/singlecore_osal.obj \
./src/srio_debug.obj \
./src/system_init.obj \
./src/system_init_var.obj \
./src/tcp3d_device.obj \
./src/tcp3d_fun.obj \
./src/tcp3d_itg.obj \
./src/tcp3d_pdsch.obj \
./src/vcp2_common.obj \
./src/view_ale_table.obj 

ASM_DEPS += \
./src/_csl_intcIntrEnDisRes.pp \
./src/_csl_intcIsrDispatch.pp 

C_DEPS += \
./src/BitDescrambling.pp \
./src/Exception.pp \
./src/FunctionHook.pp \
./src/KeyStone_DDR_Init.pp \
./src/KeyStone_Multicore_Navigator_drv.pp \
./src/KeyStone_SRIO_Init.pp \
./src/KeyStone_Timer_Init.pp \
./src/KeyStone_common.pp \
./src/Keystone_SRIO_drv.pp \
./src/Keystone_Serdes_init.pp \
./src/MNav_funct.pp \
./src/SRIO_2DSP_Test.pp \
./src/SRIO_PktDMA_Init.pp \
./src/SRIO_external_forward_back_Test.pp \
./src/SRIO_external_line_loopback_Test.pp \
./src/SRIO_internal_loopback_Test.pp \
./src/SRIO_loopback_Test.pp \
./src/TSC.pp \
./src/VCP2_Channel_Density.pp \
./src/_csl_intcResource.pp \
./src/bcp_device.pp \
./src/bcp_func.pp \
./src/bcp_lte_pdsch_receive.pp \
./src/cc_conv_decoder.pp \
./src/cc_conv_derate_matching.pp \
./src/chan_eq_sdm.pp \
./src/chan_est.pp \
./src/chan_interp.pp \
./src/classify1_bin.pp \
./src/classify2_bin.pp \
./src/cppi_desc.pp \
./src/cppi_device.pp \
./src/cppi_drv.pp \
./src/cppi_listlib.pp \
./src/crc_decoder.pp \
./src/crs_prb_demapping.pp \
./src/csl_chip.pp \
./src/dci_process.pp \
./src/demodulation.pp \
./src/fftc_func.pp \
./src/freq_agc.pp \
./src/ifft_data.pp \
./src/layerdemapping.pp \
./src/lte_dl_receiver_process.pp \
./src/osal.pp \
./src/pa.pp \
./src/painit.pp \
./src/pam_bin.pp \
./src/para_update.pp \
./src/phich_detect.pp \
./src/pl_const.pp \
./src/prb_demapping_all.pp \
./src/qmss_acc.pp \
./src/qmss_device.pp \
./src/qmss_drv.pp \
./src/rs_basic_gen.pp \
./src/singlecore_osal.pp \
./src/srio_debug.pp \
./src/system_init.pp \
./src/system_init_var.pp \
./src/tcp3d_device.pp \
./src/tcp3d_fun.pp \
./src/tcp3d_itg.pp \
./src/tcp3d_pdsch.pp \
./src/vcp2_common.pp \
./src/view_ale_table.pp 

C_DEPS__QUOTED += \
"src\BitDescrambling.pp" \
"src\Exception.pp" \
"src\FunctionHook.pp" \
"src\KeyStone_DDR_Init.pp" \
"src\KeyStone_Multicore_Navigator_drv.pp" \
"src\KeyStone_SRIO_Init.pp" \
"src\KeyStone_Timer_Init.pp" \
"src\KeyStone_common.pp" \
"src\Keystone_SRIO_drv.pp" \
"src\Keystone_Serdes_init.pp" \
"src\MNav_funct.pp" \
"src\SRIO_2DSP_Test.pp" \
"src\SRIO_PktDMA_Init.pp" \
"src\SRIO_external_forward_back_Test.pp" \
"src\SRIO_external_line_loopback_Test.pp" \
"src\SRIO_internal_loopback_Test.pp" \
"src\SRIO_loopback_Test.pp" \
"src\TSC.pp" \
"src\VCP2_Channel_Density.pp" \
"src\_csl_intcResource.pp" \
"src\bcp_device.pp" \
"src\bcp_func.pp" \
"src\bcp_lte_pdsch_receive.pp" \
"src\cc_conv_decoder.pp" \
"src\cc_conv_derate_matching.pp" \
"src\chan_eq_sdm.pp" \
"src\chan_est.pp" \
"src\chan_interp.pp" \
"src\classify1_bin.pp" \
"src\classify2_bin.pp" \
"src\cppi_desc.pp" \
"src\cppi_device.pp" \
"src\cppi_drv.pp" \
"src\cppi_listlib.pp" \
"src\crc_decoder.pp" \
"src\crs_prb_demapping.pp" \
"src\csl_chip.pp" \
"src\dci_process.pp" \
"src\demodulation.pp" \
"src\fftc_func.pp" \
"src\freq_agc.pp" \
"src\ifft_data.pp" \
"src\layerdemapping.pp" \
"src\lte_dl_receiver_process.pp" \
"src\osal.pp" \
"src\pa.pp" \
"src\painit.pp" \
"src\pam_bin.pp" \
"src\para_update.pp" \
"src\phich_detect.pp" \
"src\pl_const.pp" \
"src\prb_demapping_all.pp" \
"src\qmss_acc.pp" \
"src\qmss_device.pp" \
"src\qmss_drv.pp" \
"src\rs_basic_gen.pp" \
"src\singlecore_osal.pp" \
"src\srio_debug.pp" \
"src\system_init.pp" \
"src\system_init_var.pp" \
"src\tcp3d_device.pp" \
"src\tcp3d_fun.pp" \
"src\tcp3d_itg.pp" \
"src\tcp3d_pdsch.pp" \
"src\vcp2_common.pp" \
"src\view_ale_table.pp" 

OBJS__QUOTED += \
"src\BitDescrambling.obj" \
"src\Exception.obj" \
"src\FunctionHook.obj" \
"src\KeyStone_DDR_Init.obj" \
"src\KeyStone_Multicore_Navigator_drv.obj" \
"src\KeyStone_SRIO_Init.obj" \
"src\KeyStone_Timer_Init.obj" \
"src\KeyStone_common.obj" \
"src\Keystone_SRIO_drv.obj" \
"src\Keystone_Serdes_init.obj" \
"src\MNav_funct.obj" \
"src\SRIO_2DSP_Test.obj" \
"src\SRIO_PktDMA_Init.obj" \
"src\SRIO_external_forward_back_Test.obj" \
"src\SRIO_external_line_loopback_Test.obj" \
"src\SRIO_internal_loopback_Test.obj" \
"src\SRIO_loopback_Test.obj" \
"src\TSC.obj" \
"src\VCP2_Channel_Density.obj" \
"src\_csl_intcIntrEnDisRes.obj" \
"src\_csl_intcIsrDispatch.obj" \
"src\_csl_intcResource.obj" \
"src\bcp_device.obj" \
"src\bcp_func.obj" \
"src\bcp_lte_pdsch_receive.obj" \
"src\cc_conv_decoder.obj" \
"src\cc_conv_derate_matching.obj" \
"src\chan_eq_sdm.obj" \
"src\chan_est.obj" \
"src\chan_interp.obj" \
"src\classify1_bin.obj" \
"src\classify2_bin.obj" \
"src\cppi_desc.obj" \
"src\cppi_device.obj" \
"src\cppi_drv.obj" \
"src\cppi_listlib.obj" \
"src\crc_decoder.obj" \
"src\crs_prb_demapping.obj" \
"src\csl_chip.obj" \
"src\dci_process.obj" \
"src\demodulation.obj" \
"src\fftc_func.obj" \
"src\freq_agc.obj" \
"src\ifft_data.obj" \
"src\layerdemapping.obj" \
"src\lte_dl_receiver_process.obj" \
"src\osal.obj" \
"src\pa.obj" \
"src\painit.obj" \
"src\pam_bin.obj" \
"src\para_update.obj" \
"src\phich_detect.obj" \
"src\pl_const.obj" \
"src\prb_demapping_all.obj" \
"src\qmss_acc.obj" \
"src\qmss_device.obj" \
"src\qmss_drv.obj" \
"src\rs_basic_gen.obj" \
"src\singlecore_osal.obj" \
"src\srio_debug.obj" \
"src\system_init.obj" \
"src\system_init_var.obj" \
"src\tcp3d_device.obj" \
"src\tcp3d_fun.obj" \
"src\tcp3d_itg.obj" \
"src\tcp3d_pdsch.obj" \
"src\vcp2_common.obj" \
"src\view_ale_table.obj" 

ASM_DEPS__QUOTED += \
"src\_csl_intcIntrEnDisRes.pp" \
"src\_csl_intcIsrDispatch.pp" 

C_SRCS__QUOTED += \
"../src/BitDescrambling.c" \
"../src/Exception.c" \
"../src/FunctionHook.c" \
"../src/KeyStone_DDR_Init.c" \
"../src/KeyStone_Multicore_Navigator_drv.c" \
"../src/KeyStone_SRIO_Init.c" \
"../src/KeyStone_Timer_Init.c" \
"../src/KeyStone_common.c" \
"../src/Keystone_SRIO_drv.c" \
"../src/Keystone_Serdes_init.c" \
"../src/MNav_funct.c" \
"../src/SRIO_2DSP_Test.c" \
"../src/SRIO_PktDMA_Init.c" \
"../src/SRIO_external_forward_back_Test.c" \
"../src/SRIO_external_line_loopback_Test.c" \
"../src/SRIO_internal_loopback_Test.c" \
"../src/SRIO_loopback_Test.c" \
"../src/TSC.c" \
"../src/VCP2_Channel_Density.c" \
"../src/_csl_intcResource.c" \
"../src/bcp_device.c" \
"../src/bcp_func.c" \
"../src/bcp_lte_pdsch_receive.c" \
"../src/cc_conv_decoder.c" \
"../src/cc_conv_derate_matching.c" \
"../src/chan_est.c" \
"../src/chan_interp.c" \
"../src/classify1_bin.c" \
"../src/classify2_bin.c" \
"../src/cppi_desc.c" \
"../src/cppi_device.c" \
"../src/cppi_drv.c" \
"../src/cppi_listlib.c" \
"../src/crc_decoder.c" \
"../src/crs_prb_demapping.c" \
"../src/csl_chip.c" \
"../src/demodulation.c" \
"../src/freq_agc.c" \
"../src/ifft_data.c" \
"../src/layerdemapping.c" \
"../src/osal.c" \
"../src/pa.c" \
"../src/painit.c" \
"../src/pam_bin.c" \
"../src/para_update.c" \
"../src/phich_detect.c" \
"../src/pl_const.c" \
"../src/qmss_acc.c" \
"../src/qmss_device.c" \
"../src/qmss_drv.c" \
"../src/rs_basic_gen.c" \
"../src/singlecore_osal.c" \
"../src/srio_debug.c" \
"../src/system_init_var.c" \
"../src/tcp3d_device.c" \
"../src/tcp3d_fun.c" \
"../src/tcp3d_itg.c" \
"../src/vcp2_common.c" \
"../src/view_ale_table.c" 

ASM_SRCS__QUOTED += \
"../src/_csl_intcIntrEnDisRes.asm" \
"../src/_csl_intcIsrDispatch.asm" 


